export const CARS_TAB_CONST = {
  TEXTS: {
    title: 'Автомобили',
    addNew: 'Добави нов',
    editCar: 'Редактирай автомобил',
    addNewCar: 'Добави нов автомобил',
    basicInformation: 'Основна информация',
    brand: 'Марка',
    model: 'Модел',
    year: 'Година',
    class: 'Клас',
    classes: {
      economy: 'Икономичен',
      standard: 'Стандартен',
      premium: 'Премиум',
    },
    pricing: 'Ценообразуване',
    pricePerDay: 'Цена на ден',
    depositAmount: 'Сума на депозита',
    features: 'Екстри',
    addFeature: 'Добави екстра',
    add: 'Добави',
    description: 'Описание',
    images: 'Снимки',
    uploadImages: 'Качи снимки',
    active: 'Активен',
    inactive: 'Неактивен',
    edit: 'Редактирай',
    delete: 'Изтрий',
    perDay: 'на ден',
    deposit: 'Депозит',
    noCars: 'Няма автомобили',
    noCarsDescription: 'Все още не са добавени автомобили в системата',
    addFirstCar: 'Добави първия автомобил',
    deleteConfirmTitle: 'Потвърди изтриването',
    deleteConfirmMessage:
      'Сигурни ли сте, че искате да изтриете автомобила {{car}}?',
    calendar: 'Календар',
    carCreatedSuccess: 'Автомобилът е създаден успешно',
    carUpdatedSuccess: 'Автомобилът е редактиран успешно',
    carDeletedSuccess: 'Автомобилът е изтрит успешно',
    sessionExpired: 'Сесията ви е изтекла. Моля, влезте отново в системата.',
    saveError: 'Възникна грешка при запазване на автомобила',
    deleteError: 'Възникна грешка при изтриване на автомобила',
    conflictError: 'Не можете да изтриете автомобил с съществуващи резервации',
  },
  CURRENCY_RATE: 1.96,
  GRID_TEMPLATE: 'repeat(auto-fit, minmax(300px, 1fr))',
  CARD_HEIGHT: '100%',
  IMAGE_HEIGHT: 200,
  WARNING_MESSAGE:
    '⚠️ ВНИМАНИЕ: Ако този автомобил има активни резервации, не може да бъде изтрит!',
} as const;
