import { SxProps, Theme } from '@mui/material';

export const bookingPageClientStyles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f8f9fa',
    paddingY: 4,
  } as SxProps<Theme>,
  selectDatesContainer: {
    textAlign: 'center',
    padding: 4,
  } as SxProps<Theme>,
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    padding: 4,
  } as SxProps<Theme>,
  carsContainer: {
    marginBottom: 3,
  } as SxProps<Theme>,
  noCarsContainer: {
    textAlign: 'center',
    padding: 4,
  } as SxProps<Theme>,
  periodContainer: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    marginLeft: 1,
    padding: '8px 16px',
    backgroundColor: '#f8f9fa',
    borderRadius: 2,
    border: '1px solid #e0e0e0',
    fontSize: '0.9rem',
    color: '#666',
  } as SxProps<Theme>,
  periodContainerMobile: {
    display: 'block',
    alignItems: 'center',
    gap: 1,
    marginLeft: 0,
    padding: '8px 8px',
    backgroundColor: '#f8f9fa',
    borderRadius: 2,
    border: '1px solid #e0e0e0',
    fontSize: '0.9rem',
    color: '#666',
  } as SxProps<Theme>,
  periodLabel: {
    color: '#1976d2',
    fontWeight: 600,
  } as SxProps<Theme>,
  dateContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    padding: '4px 8px',
    backgroundColor: '#fff',
    borderRadius: 1,
    border: '1px solid #e0e0e0',
  } as SxProps<Theme>,
  dateContainerMobile: {
    display: 'grid',
    gridTemplateColumns: 'auto auto auto auto auto',
    alignItems: 'center',
    gap: 0.25,
    padding: '4px 8px 4px 8px',
    backgroundColor: '#fff',
    borderRadius: 1,
    border: '1px solid #e0e0e0',
    marginTop: 1,
  } as SxProps<Theme>,
  dateText: {
    fontWeight: 600,
    color: '#333',
    display: 'inline',
  } as SxProps<Theme>,
  dateTextMobile: {
    fontWeight: 600,
    color: '#333',
    display: 'block',
    marginBottom: 0.5,
  } as SxProps<Theme>,
  timeText: {
    color: '#1976d2',
    fontWeight: 600,
    backgroundColor: '#e3f2fd',
    padding: '2px 6px',
    borderRadius: 1,
    fontSize: '0.8rem',
    display: 'inline',
  } as SxProps<Theme>,
  timeTextMobile: {
    color: '#1976d2',
    fontWeight: 600,
    backgroundColor: '#e3f2fd',
    padding: '2px 2px',
    borderRadius: 1,
    fontSize: '0.8rem',
    display: 'block',
  } as SxProps<Theme>,
  separator: {
    color: '#666',
    fontWeight: 400,
  } as SxProps<Theme>,
  developmentBanner: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 9999,
    borderRadius: 0,
    boxShadow: 3,
  } as SxProps<Theme>,
  developmentBannerMessage: {
    fontSize: '1.1rem',
    fontWeight: 500,
  } as SxProps<Theme>,
  developmentBannerContent: {
    textAlign: 'center',
    py: 1,
  } as SxProps<Theme>,
} as const;
