export const BOOKINGS_TAB_CONST = {
  TEXTS: {
    title: 'Резервации',
    refresh: 'Обнови',
    search: 'Търсене',
    searchPlaceholder: 'Име, имейл, телефон...',
    status: 'Статус',
    allStatuses: 'Всички статуси',
    pending: 'Чакаща',
    confirmed: 'Потвърдена',
    cancelled: 'Отменена',
    depositStatus: 'Статус на депозит',
    allDepositStatuses: 'Всички депозити',
    depositPending: 'Чакащ',
    depositPaid: 'Платено',
    depositRefunded: 'Върнато',
    startDate: 'Начална дата',
    endDate: 'Крайна дата',
    clearFilters: 'Изчисти филтрите',
    car: 'Автомобил',
    client: 'Клиент',
    dates: 'Дати',
    totalPrice: 'Обща цена',
    deposit: 'Депозит',
    actions: 'Действия',
    rowsPerPage: 'Редове на страница',
    of: 'от',
    noBookings: 'Няма резервации',
    noBookingsDescription: 'Все още не са направени резервации в системата',
    carNotFound: 'Автомобилът не е намерен',
    to: 'до',
    days: 'дни',
    deleted: 'Изтрита',
    noFilteredResults: 'Няма резултати за избраните филтри',
    noFilteredResultsDescription: 'Опитайте с различни критерии за търсене',
  },
  STATUS_OPTIONS: [
    { value: '', label: 'Всички статуси' },
    { value: 'pending', label: 'Чакаща' },
    { value: 'confirmed', label: 'Потвърдена' },
    { value: 'cancelled', label: 'Отменена' },
    { value: 'deleted', label: 'Изтрита' },
  ],
  DEPOSIT_STATUS_OPTIONS: [
    { value: '', label: 'Всички депозити' },
    { value: 'pending', label: 'Чакащ' },
    { value: 'paid', label: 'Платен' },
    { value: 'refunded', label: 'Върнат' },
  ],
  ROWS_PER_PAGE_OPTIONS: [5, 10, 25, 50],
  DEFAULT_ROWS_PER_PAGE: 10,
  CURRENCY_RATE: 1.96,
} as const;
