export const CAR_CALENDAR_DIALOG_CONST = {
  TEXTS: {
    title: 'Календар за',
    availabilityCalendar: 'Календар на наличност',
    availableDates: 'Свободни дати',
    bookedDates: 'Запазени дати',
    bookings: 'Резервации',
    booking: 'Резервация',
    for: 'за',
    period: 'Период:',
    days: 'дни',
    noBookings: 'Няма резервации за този автомобил.',
    close: 'Затвори',
    loadingError: 'Грешка при зареждане на резервациите',
  },
  MONTH_NAMES: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
    'Януари',
    'Февруари',
    'Март',
    'Април',
    'Май',
    'Юни',
    'Юли',
    'Август',
    'Септември',
    'Октомври',
    'Ноември',
    'Декември',
  ],
  COLORS: {
    available: '#4caf50',
    booked: '#f44336',
  },
  CALENDAR_CLASS: 'car-calendar',
  TIMEOUT_DELAY: 100,
  OBSERVER_DELAY: 50,
} as const;
