export const CAR_FORM_DIALOG_CONST = {
  TEXTS: {
    title: 'Добавяне на автомобил',
    editTitle: 'Редактиране на автомобил',
    basicInformation: 'Основна информация',
    brand: 'Марка',
    model: 'Модел',
    year: 'Година',
    class: 'Клас',
    classes: {
      economy: 'Икономичен',
      standard: 'Стандартен',
      premium: 'Премиум',
    },
    fuelType: 'Тип гориво',
    fuelTypes: {
      gasoline: 'Бензин',
      diesel: 'Дизел',
      electric: 'Електрически',
      hybrid: 'Хибриден',
    },
    transmission: 'Трансмисия',
    transmissions: {
      manual: 'Ръчна',
      automatic: 'Автоматична',
    },
    pricePerDay: 'Цена на ден',
    depositAmount: 'Депозит',
    isActive: 'Активен',
    active: 'Активен',
    inactive: 'Неактивен',
    pricing: 'Ценообразуване',
    features: 'Екстри',
    addFeature: 'Добави екстра',
    structuredFeatures: 'Основни характеристики',
    seats: 'Места',
    largeLuggage: 'Голям куфар',
    smallLuggage: 'Малък куфар',
    doors: 'Врати',
    minAge: 'Минимална възраст',
    fourWd: '4WD задвижване',
    ac: 'Климатик',
    images: 'Снимки',
    uploadImages: 'Качи снимки',
    cancel: 'Отказ',
    save: 'Запази',
    loading: 'Зареждане...',
    mainImage: 'ГЛАВНА',
    newImage: 'НОВА',
    makeMainImage: 'Направи главна снимка',
    deleteImage: 'Изтрий снимка',
    firstImageDescription:
      'Първата снимка ще бъде използвана като заглавна навсякъде в сайта. Можеш да преместиш която и да е снимка на първо място с бутона ↑.',
  },
  CLASS_OPTIONS: [
    { value: 'economy', label: 'Икономичен' },
    { value: 'standard', label: 'Стандартен' },
    { value: 'premium', label: 'Премиум' },
  ],
  FUEL_TYPE_OPTIONS: [
    { value: 'petrol', label: 'Бензин' },
    { value: 'diesel', label: 'Дизел' },
    { value: 'hybrid', label: 'Хибрид' },
    { value: 'electric', label: 'Електрически' },
    { value: 'lpg', label: 'Газ (LPG)' },
  ],
  TRANSMISSION_OPTIONS: [
    { value: 'manual', label: 'Ръчна' },
    { value: 'automatic', label: 'Автоматична' },
    { value: 'cvt', label: 'CVT' },
    { value: 'semi-automatic', label: 'Полуавтоматична' },
  ],
  VALIDATION: {
    brandRequired: 'Марката е задължителна',
    modelRequired: 'Моделът е задължителен',
    classRequired: 'Класът е задължителен',
    fuelTypeRequired: 'Типът гориво е задължителен',
    transmissionRequired: 'Трансмисията е задължителна',
    invalidYear: 'Невалидна година',
    invalidPrice: 'Цената трябва да е по-голяма от 0',
    invalidDeposit: 'Депозитът не може да е отрицателен',
    invalidClass: 'Невалиден клас',
    invalidFuelType: 'Невалиден тип гориво',
    invalidTransmission: 'Невалидна трансмисия',
  },
  ALLOWED_CLASSES: ['economy', 'standard', 'premium'],
  ALLOWED_FUEL_TYPES: ['petrol', 'diesel', 'hybrid', 'electric', 'lpg'],
  ALLOWED_TRANSMISSIONS: ['manual', 'automatic', 'cvt', 'semi-automatic'],
  CURRENCY_RATE: 1.96,
  MIN_YEAR: 1990,
  MAX_YEAR_OFFSET: 2,
  DEFAULT_VALUES: {
    year: new Date().getFullYear(),
    seats: 5,
    largeLuggage: 1,
    smallLuggage: 1,
    doors: 4,
    minAge: 21,
    fourWd: false,
    ac: false,
    available: true,
  },
} as const;
